# /**/controller_manager: 
/**:
  ros__parameters:
    publish_cmd_freq: 100  # Hz
    publish_info_freq: 10    # Hz
    plugin_name: "controller_plugin_differential_flatness::DFPlugin"
    plugin_config_file: "path/to/config.yaml"
    plugin_available_modes_config_file: "path"
